"""
Probashi Hub (সৌদি প্রবাসী ওয়ান-স্টপ হাব)
Database Seeding Script for Supabase & Local SQL Generator
Reads data/problems.json, validates 50 records, and upserts into Supabase.
Also writes a complete database/seeds/problems.sql file.
"""

import json
import os
import sys
from pathlib import Path

# Paths
ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT_DIR / "data" / "problems.json"
SQL_OUT_PATH = ROOT_DIR / "database" / "seeds" / "problems.sql"

def escape_sql_str(value: str) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"

def generate_sql_seeds(records: list) -> str:
    sql_lines = [
        "-- ==============================================================================",
        "-- Probashi Hub: 50 Verified Saudi Expat Problem & Solution Seeds",
        "-- Auto-generated by scripts/seed_database.py",
        "-- ==============================================================================\n",
        "INSERT INTO services (",
        "    id, slug, category_id, category_name, title, title_en, summary, urgent,",
        "    official_portal, steps, required_documents, scam_warnings,",
        "    official_fees_sar, processing_time, b2b_service_category",
        ") VALUES"
    ]

    values_entries = []
    for r in records:
        entry = (
            f"(\n"
            f"    {r['id']},\n"
            f"    {escape_sql_str(r['slug'])},\n"
            f"    {r['category_id']},\n"
            f"    {escape_sql_str(r['category_name'])},\n"
            f"    {escape_sql_str(r['title'])},\n"
            f"    {escape_sql_str(r['title_en'])},\n"
            f"    {escape_sql_str(r['summary'])},\n"
            f"    {'TRUE' if r.get('urgent') else 'FALSE'},\n"
            f"    {escape_sql_str(r['official_portal'])},\n"
            f"    {escape_sql_str(json.dumps(r['steps'], ensure_ascii=False))}::jsonb,\n"
            f"    {escape_sql_str(json.dumps(r['required_documents'], ensure_ascii=False))}::jsonb,\n"
            f"    {escape_sql_str(r['scam_warnings'])},\n"
            f"    {escape_sql_str(r['official_fees_sar'])},\n"
            f"    {escape_sql_str(r['processing_time'])},\n"
            f"    {escape_sql_str(r['b2b_service_category'])}\n"
            f")"
        )
        values_entries.append(entry)

    sql_lines.append(",\n".join(values_entries))
    sql_lines.append(
        "\nON CONFLICT (slug) DO UPDATE SET\n"
        "    title = EXCLUDED.title,\n"
        "    title_en = EXCLUDED.title_en,\n"
        "    category_id = EXCLUDED.category_id,\n"
        "    category_name = EXCLUDED.category_name,\n"
        "    summary = EXCLUDED.summary,\n"
        "    urgent = EXCLUDED.urgent,\n"
        "    official_portal = EXCLUDED.official_portal,\n"
        "    steps = EXCLUDED.steps,\n"
        "    required_documents = EXCLUDED.required_documents,\n"
        "    scam_warnings = EXCLUDED.scam_warnings,\n"
        "    official_fees_sar = EXCLUDED.official_fees_sar,\n"
        "    processing_time = EXCLUDED.processing_time,\n"
        "    b2b_service_category = EXCLUDED.b2b_service_category,\n"
        "    updated_at = NOW();\n"
    )

    return "\n".join(sql_lines)

def sync_to_supabase(records: list):
    supabase_url = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
    supabase_key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

    if not supabase_url or not supabase_key:
        print("[INFO] SUPABASE credentials not detected in environment. Skipping remote HTTP sync.")
        return

    try:
        from supabase import create_client
        client = create_client(supabase_url, supabase_key)
        print(f"[INFO] Connecting to Supabase at {supabase_url}...")
        
        for r in records:
            payload = {
                "id": r["id"],
                "slug": r["slug"],
                "category_id": r["category_id"],
                "category_name": r["category_name"],
                "title": r["title"],
                "title_en": r["title_en"],
                "summary": r["summary"],
                "urgent": r.get("urgent", False),
                "official_portal": r["official_portal"],
                "steps": r["steps"],
                "required_documents": r["required_documents"],
                "scam_warnings": r["scam_warnings"],
                "official_fees_sar": r["official_fees_sar"],
                "processing_time": r["processing_time"],
                "b2b_service_category": r["b2b_service_category"]
            }
            client.table("services").upsert(payload).execute()
        print(f"[SUCCESS] Successfully seeded {len(records)} records into Supabase 'services' table!")
    except ImportError:
        print("[WARN] 'supabase' package not installed. Remote sync skipped.")
    except Exception as e:
        print(f"[ERROR] Failed to seed Supabase: {e}")

def main():
    print(f"Loading data from {DATA_PATH}...")
    if not DATA_PATH.exists():
        print(f"[ERROR] Missing {DATA_PATH}")
        sys.exit(1)

    with open(DATA_PATH, "r", encoding="utf-8") as f:
        records = json.load(f)

    print(f"Loaded {len(records)} problem datasets across {len(set(r['category_id'] for r in records))} categories.")
    assert len(records) >= 50, f"Expected 50 records, found {len(records)}"

    # Generate SQL file
    SQL_OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    sql_content = generate_sql_seeds(records)
    with open(SQL_OUT_PATH, "w", encoding="utf-8") as f:
        f.write(sql_content)
    print(f"[SUCCESS] Written SQL seeds to {SQL_OUT_PATH}")

    # Sync to Supabase if configured
    sync_to_supabase(records)

if __name__ == "__main__":
    main()
